name: dartling_dwt_todo_mvc
version: 0.0.3
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: "Todo.Mvc done with dartling and DWT. \r\nBased on TodoMVC in Dart. \r\
  \ndartling is a domain model framework. DWT is a web framework."
homepage: http://ondart.me/
documentation: http://goo.gl/Fd08zZ
environment:
  sdk: '>=0.8.10+8 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.10.0'
  dart_web_toolkit: '>=0.3.25'
  dartling: '>=1.0.1 <2.0.0'
  dartling_default_app: '>=1.0.1 <2.0.0'
