name: dartling_dwt_todo_mvc
version: 0.1.0
author: Dzenan Ridjanovic & Sergey Akopkokhyants
description: "Todo.Mvc done with dartling and DWT. \r\ndartling is a domain model\
  \ framework. DWT is a web framework."
homepage: http://ondart.me/
dependencies:
  browser: any
  dart_web_toolkit: '>=0.3.18+2'
  dartling:
    git: git://github.com/dzenanr/dartling.git
  dartling_default_app:
    git: git://github.com/dzenanr/dartling_default_app.git
