name: dartling_dwt_todo_mvc
version: 0.0.8
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: "Todo.Mvc done with dartling and DWT. \nBased on TodoMVC in Dart. \n\
  dartling is a domain model framework. DWT is a web framework."
homepage: http://ondart.me/
documentation: http://goo.gl/Fd08zZ
environment:
  sdk: '>=1.9.3 <2.0.0'
dependencies:
  browser: any
  dart_web_toolkit: any
  dartling:
    git: git://github.com/dzenanr/dartling.git
  dartling_default_app:
    git: git://github.com/dzenanr/dartling_default_app.git
